### ISSUE TITLE
Validate body

### ISSUE THREAD

**Issue by Sorikairox** [Savory/Danet#12]
When using `@Body` decorator, we should be able to validate the body we are receiving

Using our [validatte package](https://github.com/Savory/validatte), we should validate bodies.

This should be an opt-out feature, we validate by default.

opt-out may look like this : 

```typescript
export const bootstrap = async () => {
  const application = new DanetApplication();
  application.disableBodyValidation();
  await application.init(AppModule);
  return application;
}
```

Upon injecting the body in `router.ts` we can validate it, and throws a 400 Bad Request containing `validateObject` return value.

**Comment by talis-fb** [comment]
I could take this issue. But it isn't totally clear for me what exactly you mean with "validate" the body. I took a look at Body decorator's code and saw that the value of body is extracted inside a try catch block. 

The validation would be to change the simple _throw e_ by a handler to return a 400 Bad Request?? 

![image](https://user-images.githubusercontent.com/54823205/193949169-7343313c-e949-4578-a069-9430216d775f.png)

**Comment by Sorikairox** [comment]
Hi @talis-fb , thank you for coming here !

Here is an example of usage for the new feature requested by this issue :

First, we define how our body should look like by defining a class and using our package 'validatte'.
```ts
class MyBodyDTO {
 @IsString()
 @IsEmail()
 public email:string;

 @IsString()
 @LengthGreaterThan(5)
 public username: string;
}
```

The `@Body` decorator should, if user has not opt-out the body validation, call 'validatte' function `validateObject` on the body to ensure the body is a correct `MyBodyDTO`.

If not, it should throw a 400 with detailed error.

Hope this help !

**Comment by talis-fb** [comment]
Yeah! It helped me a lot! Thanks for explaination =D. I'll work on the feature!

**Comment by Sorikairox** [comment]
@talis-fb Cool ! Feel free to join our discord https://discord.gg/Q7ZHuDPgjA
