### ISSUE TITLE
HTTP engine abstraction

### ISSUE THREAD

**Issue by Sorikairox** [Savory/Danet#29]
For now, `DanetApplication` references an `oak` Application. We should abstract it to prepare for other HTTP engines

**Comment by shevernitskiy** [comment]
According this bench oak is not so performant -> https://github.com/denosaurs/bench
It's like express in node world:)
Waiting for http abstraction...

**Comment by the-jk3** [comment]
Hi, I'd like to take care of this issue

**Comment by Sorikairox** [comment]
Sure

**Comment by boywithkeyboard** [comment]
@Sorikairox cheetah will hit v1.0 on July 7 and I'd like to partner up with you, so people can choose between these two.

**Comment by jlucaso1** [comment]
`Deno.serve` is stable and would be a good alternative.

**Comment by Sorikairox** [comment]
We moved from Oak to Hono in V2. Not planning to handle multiple engine for now, closing this issue.
