### ISSUE TITLE
@Session decorator

### ISSUE THREAD

**Issue by Sorikairox** [Savory/Danet#31]
We should be able to get the session in controllers' methods without using `@Req` decorator, using a new decorator `@Session`.

It could either take a parameter to return a specific attribute, or no parameter to return the whole session.

It would be used as follow : 

```typescript

class CustomSessionContent {
   userId: string;
   userToken: string;
}

@Controller('')
export class AppController {
  constructor() {
  }

  @Get()
  helloWorld(@Session() mySession: CustomeSessionContent, @Session('userId') userId: string) {
  }
}

```

**Comment by affanmustafa** [comment]
Hi @Sorikairox, I saw your post on Hacktoberfest discord. Could I contribute to this?

**Comment by Sorikairox** [comment]
Hi @affanmustafa, of course !

**Comment by ST1LLWATER** [comment]
Hey can you assign this issue to me I would like to work on this!

**Comment by vaibhavg20comp** [comment]
Hello I am an absolute beginner in open-source and want to start with this one. Can you assign this issue to me  ?

**Comment by Sorikairox** [comment]
@vaibhavg20comp you can start working on it without me assigning you !

**Comment by Sorikairox** [comment]
Doing it, should be out by November 3 !

**Comment by Sorikairox** [comment]
Middleware system must be done first. It's a WIP !
