### ISSUE TITLE
does not provide an export named 'Reflect' 

### ISSUE THREAD

**Issue by bobwatcherx** [Savory/Danet#34]
info:
deno 1.24.3 (release, x86_64-pc-windows-msvc)                                                                    v8 10.4.132.20                                                                                                   typescript 4.7.4   

deno run  -A main.ts 
                                                          error: Uncaught SyntaxError: The requested module './Reflect.ts' does not provide an export named 'Reflect'      export { Reflect } from "./Reflect.ts";

**Comment by Sorikairox** [comment]
Hi @bobwatcherx, I am missing something, can you tell me what main.ts are you running?

**Comment by bobwatcherx** [comment]
app.ts file
```
import { Module } from 'https://deno.land/x/danet/mod.ts';
import { CatsController } from './main.ts';

@Module({
  controllers: [CatsController],
})
export class AppModule {}
```

main.ts
```
import { Controller, Get } from 'https://deno.land/x/danet/mod.ts';

@Controller('cats')
export class CatsController {
  @Get()
  findAll(): string {
    return 'This action returns all cats';
  }
}
```

**Comment by Sorikairox** [comment]
Thanks, @bobwatcherx, I'm investigating this right now.

**Comment by Sorikairox** [comment]
@bobwatcherx You are trying to run a module, that will not work. It would be best/easier if you cloned our starter repository https://github.com/Savory/Danet-Starter

**Comment by Sorikairox** [comment]
Our documentation lacks the necessary code example. I am improving this now.

**Comment by Sorikairox** [comment]
We now provide the necessary code sample in the documentation. Closing this issue.

**Comment by Sorikairox** [comment]
@bobwatcherx The Reflect issue is actually tracked by deno team https://github.com/denoland/deno/issues/15197

My advice would be to use an older version such as  1.20.6

**Comment by Sorikairox** [comment]
@bobwatcherx I published a new version with another package to handle metadata.

You can now use v0.6.4 without any issues.
