### ISSUE TITLE
deploy on deno deploy

### ISSUE THREAD

**Issue by elycheikhsmail** [Savory/Danet#41]
rest api build using danet can be deployed using deno deploy ?

**Comment by Sorikairox** [comment]
Hello @elycheikhsmail !

We never tried to. I will check this tomorrow.
However, if you would like to try and give us a feedback in the meantime, feel free to do so !

Have a great day !

**Comment by Sorikairox** [comment]
Deno deploy seems to ignore `compilerOptions`, so for now, project cannot be deployed as Deploy won't handle Decorators.
Waiting for a feedback on their side

**Comment by elycheikhsmail** [comment]
thank you

**Comment by Sorikairox** [comment]
Issue is known on their side since last year. https://github.com/denoland/deploy_feedback/issues/119

We'll see if they fix that one day.

**Comment by maplecfiv** [comment]
As far as I know, ```unstable``` APIs are not supported in Deno Deploy (see [here](https://deno.com/deploy/docs/runtime-api#deno-apis) and [here](https://deno.land/manual@v1.25.3/typescript/configuration)).
 
And the option Danet used is in [unstable API list](https://doc.deno.land/deno/unstable@v1.21.2/~/Deno.CompilerOptions)

```
"compilerOptions": {
  "emitDecoratorMetadata": true
}
```

For now, it seems not possible to run Danet on Deno Deploy

**Comment by elycheikhsmail** [comment]
> As far as I know, `unstable` APIs are not supported in Deno Deploy (see [here](https://deno.com/deploy/docs/runtime-api#deno-apis) and [here](https://deno.land/manual@v1.25.3/typescript/configuration#how-deno-uses-a-configuration-file)).
> 
> And the option Danet used is in [unstable API list](https://doc.deno.land/deno/unstable@v1.21.3/~/Deno.CompilerOptions) and removed in [1.22.0](https://github.com/denoland/deno/pull/14463/commits)
> 
> ```
> "compilerOptions": {
>   "emitDecoratorMetadata": true
> }
> ```
> 
> For now, it seems not possible to run Danet on Deno Deploy

I think it nedds build step befor deploy, this may be possible solution

**Comment by maplecfiv** [comment]
> > As far as I know, `unstable` APIs are not supported in Deno Deploy (see [here](https://deno.com/deploy/docs/runtime-api#deno-apis) and [here](https://deno.land/manual@v1.25.3/typescript/configuration#how-deno-uses-a-configuration-file)).
> > And the option Danet used is in [unstable API list](https://doc.deno.land/deno/unstable@v1.21.3/~/Deno.CompilerOptions) and removed in [1.22.0](https://github.com/denoland/deno/pull/14463/commits)
> > ```
> > "compilerOptions": {
> >   "emitDecoratorMetadata": true
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For now, it seems not possible to run Danet on Deno Deploy
> 
> I think it needs build step befor deploy, this may be possible solution

> Deno deploy seems to ignore `compilerOptions`, so for now, project cannot be deployed as Deploy won't handle Decorators. Waiting for a feedback on their side

I just cloned the starter project 
Except bumping Danet version, it can link to deno deploy without error

**Comment by elycheikhsmail** [comment]
now decorator are stable in ts v5.0.0 that included in deno latest version, does this means deno deploy support danet project ?

**Comment by Sorikairox** [comment]
Without any build step. You can use the following command to compile your Danet project, and you can then run this executable on deploy !

`deno bundle run.ts bundle.js && deno compile bundle.js`

**Comment by Sorikairox** [comment]
We published a step by step guide here : 

https://savory.github.io/Danet/deno-deploy/
