### ISSUE TITLE
[DOCS] Link License and Contributing.md to ReadMe

### ISSUE THREAD

**Issue by shashankbhatgs** [Savory/Danet#42]
**Is your feature request related to a problem? Please describe.**
- Improving the docs by adding the License and contributing.md links to the ReadMe file. 

**Describe the solution you'd like** 
- I would like to add the links of LICENSE and Contributing.md at the bottom of the readme file.

**Describe alternatives you've considered** 
-

**Additional context**
-

**Comment by shashankbhatgs** [comment]
@Sorikairox can you assign this to me? also, can you add hacktoberfest label?

**Comment by dharmikjethva30** [comment]
is issue solved  or else i would like to work on it.

**Comment by Sorikairox** [comment]
Sorry @dharmikjethva30 it is solved already

**Comment by dharmikjethva30** [comment]
please close it then !
