### ISSUE TITLE
Implement recommended community standards to the project

### ISSUE THREAD

**Issue by orama254** [Savory/Danet#44]
**Is your feature request related to a problem? Please describe.** 

I was going though this project and noticed that there are some missing items based on the [Github Community Standards recommendations](https://github.com/Savory/Danet/community) that would make the project contributor friendly, e.g. a code of conduct and a pull request template.

**Describe the solution you'd like** 

Let me know if this is something you would like to implement on this project.

**Comment by Sorikairox** [comment]
Hey ! This sound good !

**Comment by orama254** [comment]
awesome @Sorikairox 

I'm sending a pull request in few minutes, feel free to assign me this task
