### ISSUE TITLE
auth modules as referance

### ISSUE THREAD

**Issue by elycheikhsmail** [Savory/Danet#54]
I think there a need for auth modules as referance, in starter repo or in other place. I suggess so because most project need auth.

**Comment by Sorikairox** [comment]
Are you asking for guards (https://savory.github.io/Danet/overview/guards/) example + a module that handles registration + login ?

**Comment by elycheikhsmail** [comment]
> Are you asking for guards (https://savory.github.io/Danet/overview/guards/) example + a module that handles registration + login ?

excatly

**Comment by Sorikairox** [comment]
Okay, that would be in the Starter repo: https://github.com/Savory/Danet-Starter !
Great request !

**Comment by Sorikairox** [comment]
This will come in the new SAASKit starter in the following weeks !
