### ISSUE TITLE
SetMetadata function to create decorators

### ISSUE THREAD

**Issue by Sorikairox** [Savory/Danet#58]
**Is your feature request related to a problem? Please describe.** 

If I want to set a controller/method metadata, for example with a `Public` decorator, I have to create it as follows: 

```ts
export const IS_PUBLIC_KEY = 'isPublic';
export const Public = () =>
(
	// deno-lint-ignore ban-types
	target: ControllerConstructor | Object,
	propertyKey?: string | symbol,
	// deno-lint-ignore no-explicit-any
	descriptor?: TypedPropertyDescriptor<any>,
) => {
	if (propertyKey && descriptor) {
		MetadataHelper.setMetadata(
			IS_PUBLIC_KEY,
			true,
			descriptor.value,
		);
	} else {
		MetadataHelper.setMetadata(IS_PUBLIC_KEY, true, target);
	}
};
```
This is way too verbose, especially when creating multiple decorators that only set metadata.

**Describe the solution you'd like** 

We should create a `SetMetadata` function to be used as follows: 

```ts
export const IS_PUBLIC_KEY = 'isPublic';
export const Public = () => SetMetadata(IS_PUBLIC_KEY, true);
```

**Comment by Niravprajapati1** [comment]
Can i work on this issue ?

**Comment by Sorikairox** [comment]
@Niravprajapati1 sure go ahead

**Comment by Niravprajapati1** [comment]
where do i want to add this function?

**Comment by Niravprajapati1** [comment]
How can i make this function i am begginer so i need some help !
