### ISSUE TITLE
Support for simple mongodb paths

### ISSUE THREAD

**Issue by RussellBrand** [Savory/Danet#59]
My mongo database is at

'mongodb://127.0.0.1:27017/exp_danet'

I can directly alter 

    mongodb.service.ts

but would nice to be able to specify it in .env

**Comment by Sorikairox** [comment]
Using dotenv.config from `https://deno.land/x/dotenv/mod.ts` you can use `.env` file with `config({ export: true });`

Then you can use `Deno.env` to get environment variables.

Here is some sample code from our starter-repository to set a connection string for mongodb:

```ts
const connectionString = `mongodb+srv://${Deno.env.get('DB_USERNAME')}:${
      Deno.env.get('DB_PASSWORD')
    }@${Deno.env.get('DB_HOST')}/${
      Deno.env.get('DB_NAME')
    }?authMechanism=SCRAM-SHA-1`;
```

I suggest you to use https://github.com/Savory/Danet-CLI to set up your Danet project, you can choose MongoDB as your db provider and all the necessary code (including getting variables from env) will be created for you !
