### ISSUE TITLE
Trying to download the cli

### ISSUE THREAD

**Issue by guzman109** [Savory/Danet#89]
**Describe the bug** A clear and concise description of what the bug is.
deno install --allow-read --allow-write --allow-run --allow-env -n danet https://deno.land/x/danet_cli/main.ts

⚠️ `deno install` behavior will change in Deno 2. To preserve the current behavior use the `-g` or `--global` flag.
error: The module's source code could not be parsed: Expected ';', got '=' at https://deno.land/x/danet_cli@0.8.1/bundle.ts:8:45

  	options: { entrypoint: string, bundlePath = './bundle' },

**Desktop (please complete the following information):**

Kubuntu 24.04

Deno 1.43.4

**Comment by Sorikairox** [comment]
Sorry about this. Fixed it in version 0.8.2. Please try again !

**Comment by guzman109** [comment]
Looks like its still trying to use 0.8.1
