### ISSUE TITLE
Fastify support

### ISSUE THREAD

**Issue by CaioF** [Savory/Danet#93]
**Is your feature request related to a problem? Please describe.** Speed/efficiency is one of the main reasons for someone to consider deno, however danet makes use of hono which is around 2x slower than fastify 

**Describe the solution you'd like** An option to use fastify instead of hono

**Describe alternatives you've considered** not sure what alternative, express is not really that interesting.

**Additional context** https://web-frameworks-benchmark.netlify.app/compare?f=nestjs-fastify,hono-deno

**Comment by Sorikairox** [comment]
Thanks for opening this issue.

I've seen completely different results https://github.com/denosaurs/bench

But also not a priority to handle. Fastify is a node framework, Hono handles Deno natively.

I will close this.
